# Generated by Django 4.2.1 on 2023-05-22 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_phone', models.PositiveIntegerField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=30, null=True)),
                ('spotify_artist_id', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(editable=False, null=True)),
                ('concerts', models.PositiveIntegerField(default=0)),
                ('sold_albums', models.PositiveIntegerField(default=0)),
                ('members', models.ManyToManyField(blank=True, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_managing_bands', 'View managing bands'), ('my_view_band', 'View band')),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bands', models.ManyToManyField(related_name='genres', to='band.band')),
            ],
        ),
    ]
