# Generated by Django 4.2.1 on 2023-05-22 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('band', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venue', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('band_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ticket_price_member', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ticket price member')),
                ('ticket_price_non_member', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ticket price non-member')),
                ('total_tickets_for_sale', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[(' ', '-'), ('r', 'Rejected'), ('a', 'Accepted'), ('c', 'Cancelled'), ('e', 'Offer sent'), ('b', 'Offer accepted'), ('d', 'Offer rejected'), ('x', 'Replaced')], default=' ', max_length=1)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='band.band')),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replacements', to='booking.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='venue.venue')),
            ],
            options={
                'permissions': (('accept_booking', 'Accept or reject booking'), ('transition_booking', 'Transition the booking state'), ('my_view_booking', 'View booking')),
            },
        ),
        migrations.CreateModel(
            name='TechnicalRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField()),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_req', to='booking.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_sold_member', models.IntegerField()),
                ('ticket_sold_non_member', models.IntegerField()),
                ('additional_information', models.TextField(blank=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='booking.booking')),
            ],
        ),
        migrations.CreateModel(
            name='BookingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.IntegerField(choices=[(0, 'Create'), (1, 'Transition')])),
                ('pre_transition_state', models.CharField(blank=True, choices=[(' ', '-'), ('r', 'Rejected'), ('a', 'Accepted'), ('c', 'Cancelled'), ('e', 'Offer sent'), ('b', 'Offer accepted'), ('d', 'Offer rejected'), ('x', 'Replaced')], max_length=1, null=True)),
                ('transition', models.CharField(blank=True, choices=[('a', 'Accept'), ('r', 'Reject'), ('o', 'Send offer'), ('m', 'Replace'), ('c', 'Cancel')], max_length=1, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='booking.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
