# Generated by Django 4.2.1 on 2023-05-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('crowd_capacity', models.IntegerField()),
                ('stage_width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stage_depth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stage_height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(editable=False, null=True)),
            ],
            options={
                'permissions': (('my_view_venue', 'View venue'),),
            },
        ),
    ]
